# Generated by Django 2.1.7 on 2019-03-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adddiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
