# Generated by Django 2.1.7 on 2019-03-31 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190331_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
